name: nasa_apod
description: "A Flutter app showing the APOD."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  api:
    path: modules/api

  injectable: ^2.3.2
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.3.2
  build_runner: ^2.4.8

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
