name: api
description: "The API module."

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.7
  http: ^1.2.0
  json_annotation: ^4.8.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.3.2
  build_runner: ^2.4.8

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
